import customtkinter as ctk
import tkinter as tk
ctk.set_appearance_mode("light")
ctk.set_default_color_theme("dark-blue")
class App(ctk.CTk):
    def __init__(self,*args):
        super().__init__(*args)
        self.title("Advance Calculator")
        self.geometry("420x320")
        self.resizable(False,False)
        self.inputlabel=ctk.CTkEntry(self,placeholder_text="Enter Something to Calculate")
        self.inputlabel.grid(row=0,column=0,columnspan=6,padx=5,pady=5,sticky="ew")
        self.one=ctk.CTkButton(self,text="1",width=60,fg_color="#660066")
        self.one.grid(row=1,column=0,padx=5,pady=5,sticky="ew")
        self.two=ctk.CTkButton(self,text="2",width=60,fg_color="#660066")
        self.two.grid(row=1,column=1,padx=5,pady=5,sticky="ew")
        self.three=ctk.CTkButton(self,text="3",width=60,fg_color="#660066")
        self.three.grid(row=1,column=2,padx=5,pady=5,sticky="ew")
        self.four=ctk.CTkButton(self,text="4",width=60,fg_color="#660066")
        self.four.grid(row=2,column=0,padx=5,pady=5,sticky="ew")
        self.five=ctk.CTkButton(self,text="5",width=60,fg_color="#660066")
        self.five.grid(row=2,column=1,padx=5,pady=5,sticky="ew")
        self.six=ctk.CTkButton(self,text="6",width=60,fg_color="#660066")
        self.six.grid(row=2,column=2,padx=5,pady=5,sticky="ew")
        self.seven=ctk.CTkButton(self,text="7",width=60,fg_color="#660066")
        self.seven.grid(row=3,column=0,padx=5,pady=5,sticky="ew")
        self.eight=ctk.CTkButton(self,text="8",width=60,fg_color="#660066")
        self.eight.grid(row=3,column=1,padx=5,pady=5,sticky="ew")
        self.nine=ctk.CTkButton(self,text="9",width=60,fg_color="#660066")
        self.nine.grid(row=3,column=2,padx=5,pady=5,sticky="ew")
        self.zero=ctk.CTkButton(self,text="0",width=60,fg_color="#660066")
        self.zero.grid(row=4,column=0,padx=5,pady=5,sticky="ew")
        self.dot=ctk.CTkButton(self,text=".",width=60,fg_color="#660066")
        self.dot.grid(row=4,column=2,padx=5,pady=5,sticky="ew")
        self.clear=ctk.CTkButton(self,text="C",fg_color="grey",height=70,width=60)
        self.clear.grid(row=4,column=1,padx=5,pady=5,sticky="ew",rowspan=2)
        self.plus=ctk.CTkButton(self,text="+",width=60,fg_color="#660066")
        self.plus.grid(row=5,column=0,padx=5,pady=5,sticky="ew")
        self.minus=ctk.CTkButton(self,text="-",width=60,fg_color="#660066")
        self.minus.grid(row=5,column=2,padx=5,pady=5,sticky="ew")
        self.multiply=ctk.CTkButton(self,text="*",width=60,fg_color="#660066")
        self.multiply.grid(row=6,column=0,padx=5,pady=5,sticky="ew")
        self.divide=ctk.CTkButton(self,text="/",width=60,fg_color="#660066")
        self.divide.grid(row=6,column=1,padx=5,pady=5,sticky="ew")
        self.percent=ctk.CTkButton(self,text="%",width=60,fg_color="#660066")
        self.percent.grid(row=6,column=2,padx=5,pady=5,sticky="ew")
        self.calculate=ctk.CTkButton(self,text="Calculate",fg_color="#ff0066",command=calc)
        self.calculate.grid(row=7,column=0,padx=5,pady=5,sticky="ew",columnspan=5)
        self.weight=ctk.CTkButton(self,text="Weight",width=60,fg_color="#ff3399",command=weightcalc)
        self.weight.grid(row=1,column=4,padx=5,pady=5,sticky="ew")
        self.Scientific=ctk.CTkButton(self,text="Scientific",width=60,fg_color="#ff3399",command=sciencecalc)
        self.Scientific.grid(row=2,column=4,padx=5,pady=5,sticky="ew")
        self.data=ctk.CTkButton(self,text="Data",width=60,fg_color="#ff3399",command=datacalc)
        self.data.grid(row=3,column=4,padx=5,pady=5,sticky="ew")
        self.length=ctk.CTkButton(self,text="Length",width=60,fg_color="#ff3399",command=lengthcalc)
        self.length.grid(row=4,column=4,padx=5,pady=5,sticky="ew")
        self.age=ctk.CTkButton(self,text="Age",width=60,fg_color="#ff3399",command=agecalc)
        self.age.grid(row=5,column=4,padx=5,pady=5,sticky="ew")
        self.area=ctk.CTkButton(self,text="Area",width=60,fg_color="#ff3399",command=areacalc)
        self.area.grid(row=6,column=4,padx=5,pady=5,sticky="ew")
        self.bmi=ctk.CTkButton(self,text="BMI",width=60,fg_color="#ff3399",command=bmicalc)
        self.bmi.grid(row=6,column=4,padx=5,pady=5,sticky="ew")
        self.numeral=ctk.CTkButton(self,text="Numeral System",width=60,fg_color="#ff3399",command=numeralcalc)
        self.numeral.grid(row=1,column=5,padx=5,pady=5,sticky="ew")
        self.tempreture=ctk.CTkButton(self,text="Tempreture",width=60,fg_color="#ff3399",command=temprcalc)
        self.tempreture.grid(row=2,column=5,padx=5,pady=5,sticky="ew")
        self.date=ctk.CTkButton(self,text="Date",width=60,fg_color="#ff3399",command=datecalc)
        self.date.grid(row=3,column=5,padx=5,pady=5,sticky="ew")
        self.discount=ctk.CTkButton(self,text="Discount",width=60,fg_color="#ff3399",command=discountcalc)
        self.discount.grid(row=4,column=5,padx=5,pady=5,sticky="ew")
        self.mass=ctk.CTkButton(self,text="Mass",width=60,fg_color="#ff3399",command=masscalc)
        self.mass.grid(row=5,column=5,padx=5,pady=5,sticky="ew")
        self.speed=ctk.CTkButton(self,text="Speed",width=60,fg_color="#ff3399",command=speedcalc)
        self.speed.grid(row=6,column=5,padx=5,pady=5,sticky="ew")
        self.volume=ctk.CTkButton(self,text="Volume",width=60,fg_color="#ff3399",command=volumecalc)
        self.volume.grid(row=7,column=5,padx=5,pady=5,sticky="ew")   

def calc():
    a=(1+2/3-6+20)
    b=float(a)
    print(b)
             
def weightcalc():
    weightcalcwindow=ctk.CTkToplevel(app)
    weightcalcwindow.title("Calculate Weight") 
    weightcalcwindow.geometry("400x400")
    weightcalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(weightcalcwindow,text="WEIGHT CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    weightcalcwindow.mainloop()
            
def sciencecalc():
    sciencecalcwindow=ctk.CTkToplevel(app)
    sciencecalcwindow.title("Calculate Sciene") 
    sciencecalcwindow.geometry("400x400")
    sciencecalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(sciencecalcwindow,text="SCIENCE CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    sciencecalcwindow.mainloop()

def datacalc():
    datacalcwindow=ctk.CTkToplevel(app)
    datacalcwindow.title("Calculate Data") 
    datacalcwindow.geometry("400x400")
    datacalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(datacalcwindow,text="DATA CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    datacalcwindow.mainloop()

def lengthcalc():
    lengthcalcwindow=ctk.CTkToplevel(app)
    lengthcalcwindow.title("Calculate Length") 
    lengthcalcwindow.geometry("400x400")
    lengthcalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(lengthcalcwindow,text="LENGTH CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    lengthcalcwindow.mainloop()

def agecalc():
    agecalcwindow=ctk.CTkToplevel(app)
    agecalcwindow.title("Calculate Age") 
    agecalcwindow.geometry("400x400")
    agecalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(agecalcwindow,text="AGE CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    agecalcwindow.mainloop()

def areacalc():
    areacalcwindow=ctk.CTkToplevel(app)
    areacalcwindow.title("Calculate Area") 
    areacalcwindow.geometry("400x400")
    areacalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(areacalcwindow,text="AREA CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    areacalcwindow.mainloop()

def bmicalc():
    bmicalcwindow=ctk.CTkToplevel(app)
    bmicalcwindow.title("Calculate BMI") 
    bmicalcwindow.geometry("400x400")
    bmicalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(bmicalcwindow,text="BMI CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0,columnspan=2,padx=10,pady=10)
    w=ctk.CTkOptionMenu(bmicalcwindow,values=['Kilograms','Pounds'],width=100)
    w.grid(row=1,column=0,padx=10,pady=10)
    w1=ctk.CTkEntry(bmicalcwindow,placeholder_text="Enter Values")
    w1.grid(row=2,column=0,padx=10,pady=10)
    h=ctk.CTkOptionMenu(bmicalcwindow,values=['Centimeters','Meters','Feet','Inches'],width=100)
    h.grid(row=1,column=1,padx=10,pady=10)
    h1=ctk.CTkEntry(bmicalcwindow,placeholder_text="Enter Values")
    h1.grid(row=2,column=1,padx=10,pady=10)
    bmicalcwindow.mainloop()

def numeralcalc():
    numeralcalcwindow=ctk.CTkToplevel(app)
    numeralcalcwindow.title("Calculate Numerals") 
    numeralcalcwindow.geometry("400x400")
    numeralcalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(numeralcalcwindow,text="MUMERAL CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    numeralcalcwindow.mainloop()
    
def temprcalc():
    tempwindow=ctk.CTkToplevel(app)
    tempwindow.title("Calculate Tempreture") 
    tempwindow.geometry("400x400")
    tempwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(tempwindow,text="TEMPRETURE CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    tempwindow.mainloop()

def datecalc():
    datecalcwindow=ctk.CTkToplevel(app)
    datecalcwindow.title("Calculate Date") 
    datecalcwindow.geometry("400x400")
    datecalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(datecalcwindow,text="DATE CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    datecalcwindow.mainloop()

def discountcalc():
    discountcalcwindow=ctk.CTkToplevel(app)
    discountcalcwindow.title("Calculate Discount") 
    discountcalcwindow.geometry("400x400")
    discountcalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(discountcalcwindow,text="DISCOUNT CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    discountcalcwindow.mainloop()

def masscalc():
    masscalcwindow=ctk.CTkToplevel(app)
    masscalcwindow.title("Calculate Mass") 
    masscalcwindow.geometry("400x400")
    masscalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(masscalcwindow,text="MASS CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    masscalcwindow.mainloop()   
    
def speedcalc():
    speedcalcwindow=ctk.CTkToplevel(app)
    speedcalcwindow.title("Calculate Speed") 
    speedcalcwindow.geometry("400x400")
    speedcalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(speedcalcwindow,text="SPEED CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    speedcalcwindow.mainloop()   

def volumecalc():
    volumecalcwindow=ctk.CTkToplevel(app)
    volumecalcwindow.title("Calculate Volume") 
    volumecalcwindow.geometry("400x400")
    volumecalcwindow.resizable(False,False)   
    headlabel=ctk.CTkLabel(volumecalcwindow,text="VOLUME CALCULATOR",fg_color="#660066",text_color="white")
    headlabel.grid(row=0,column=0)
    volumecalcwindow.mainloop()
    
if __name__=="__main__":
    app=App()
    app.mainloop()
